### ISSUE TITLE
MVP master story

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#104]
In scope:
- [x] Tasks and questionnaire comes from local data in app 
- [ ] See #72 for data model (still subject to refinement)
- [ ] See [here for information on LTR](https://material.io/design/usability/bidirectionality.html#mirroring-layout)
- [x] #105 Welcome screen with language selection
- [x] #106 Language switcher in header 
- [x] #107 Home page (“How can we help you today?”) 
- [x] #108 Explore-all
- [x] #109 Explore Section - Related tasks and articles
- [x] #110 Article with related tasks and articles
- [x] #111 Related tasks and articles on Task detail page
- [x] #112 The simplest possible recommendation engine, maybe just the ones recommended to everybody
- [x] #80 Questionnaire, with styling (checkboxes and radio buttons) 
- [x] #82 My Plan task list, with styling
- [x] #86 Implement task state machine
- [x] #113 Notifications - Simple example of notification when completing a task 
- [x] #84 Service search (api call to server), services without styling
- [x] #44 Task Detail, some of this is out of scope for #44 but on scope for MVP, need another story: simple implementation includes: Mark as done / Done / Add to My Plan buttons, Information tab, Find Services tab, 
- [x] #114 Some NCG data from local data in app 

Out of scope:
* Welcome / onboarding video 
* “Need help?” button and Help page contents 
* “Search for topic or service near you” - needs more discussion and wireframing 
* My Plan (onboarding) tutorial overlays 
* Notifications - notifications architecture - needs discussion / research
* Questionnaire - advanced user elements like conditional logic, sliders, accordions, etc
* Recommendation algorithm
* Support for “Updated” tasks since original set was imported 
* User login / profile “saving” 
* Edit Profile link to overlay menu 
* Task Detail - share buttons, deep linking support, additional context help overlays (why was this recommended) 
* Saving user state to server
* Fancy language switcher
* User sign in/account creation
* User account management screens 
* Tasks and questionnaire comes from server
* Some NCG data imported into the server
* Glossary 
* Advanced swipe gestures 
* Server - all content management user interface
