### ISSUE TITLE
Feedback release checklist

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1254]
List of things we need to do during the production release process 

### Acceptance Criteria 
- [x] Create production branch for `pathways-frontend`, `pathways-backend`, `content`
- [x] Add Google Play and Apple Store screenshots
- [x] Ensure all copy in French use `’` instead of `'` in Google Play and Apple Store
- [x] Add release notes to both Google Play and Apple Store

**Comment by tomy-pg** [comment]
Both stores have approved our app. Closing.
