### ISSUE TITLE
Feedback point release checklist

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1257]
This is a list of everything we need to complete as part of this release

### Acceptance Criteria 
- [x]  write release notes that will be displayed on Apple and Google Play stores
- [x] translate the release notes
- [x] add release notes to Apple Store 
- [x] add release notes to Google stores
- [x] use localized screenshots from production release 1.46.0 for Apple Store
- [x] use localized screenshots from production release 1.46.0 for Google Play Store

**Comment by tomy-pg** [comment]
Release notes:

Thanks for using Arrival Advisor! We've made updates and improvements to make your experience even better.

What's new
• Privacy policy for our "Suggest an update" feature is now translated into all 7 languages.
• Made improvements to our "Suggest an update" feature. Try it out! When you search for a service, if you see any missing or incorrect information about the listed service, feel free to click the "Suggest an update" button to let the Arrival Advisor team know to fix it.
