### ISSUE TITLE
Organizations production release checklist

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1338]
This is a list of everything we need to complete as part of this release. Please add what is missing.

**To-Do by January 18**
- [x] write release notes that will be displayed on Apple and Google Play stores
- [x] collect strings for translation from app `yarn extract-strings`
- [x] collect strings from Feedback 2.0 design mocks and place into csv

### To-Do Translation:
- [x] translate Feedback 2.0 app strings and release notes.

### Data
List things that we need to remember to think about when it comes to service data to be part of the organizations release of the app:

- [ ] Review topic-services and keep an eye out for new services that may be missed because they have not been tagged with the old-style bc211 taxonomy terms
- [ ] Import manually crafted CSV files from Jean with school, library, rec centre, etc. data
- [ ] Ensure that manually crafted CSV have primary ids populated, create tool to generate uuids for these if needed

### Release:
- [ ] Swap Algolia index for with data dump from latest BC211 data. 
- [ ] add release notes to Apple Store
- [ ] add release notes to Google stores

**Comment by cherrielam** [comment]
**Release notes:**

Thanks for using Arrival Advisor! We've made updates and improvements to make your experience even better.

What's new
• We've added Organizations to Arrival Advisor! You can now view contact information and descriptions for organizations that provide a variety of services to support newcomers.
• Tell us about your experience with services! You can give feedback about a service by selecting the smiley faces at the bottom of a service page and providing an optional comment about your experience.
• Fixed: Previously, information for many public libraries was missing when you used our service search. We've now fixed this. You can now find listings for most local public libraries within the app.

**Comment by jparlina** [comment]
Thanks @cherrielam! 
My suggestion for the third bullet point:
• Fixed: Previously, only the main branches of public libraries are listed on the app. You can now find branch locations for public libraries near you.

**Comment by cherrielam** [comment]
Updated! Thanks @jparlina
