### ISSUE TITLE
Incorporate translated UX strings - MB batch 2

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1617]
The following will be translated and should be incorporated:

- [ ] String about change of locale when locale is not available (referenced in #[1514](https://github.com/pg-irc/pathways-frontend/issues/1514)

- [ ] Onboarding copy 3 about bookmarks (referenced in #[1564](https://github.com/pg-irc/pathways-frontend/issues/1564))

- [ ] Search copy about bookmarks (referenced in #[1564](https://github.com/pg-irc/pathways-frontend/issues/1564))

- [ ] App store descriptions

- [ ] Release notes

**Comment by alysha-PG** [comment]
outstanding issues on this duped with #662
