### ISSUE TITLE
Master story: Update to new BC Newcomers' Guide

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1839]
See https://app.mural.co/t/peacegeeks4777/m/peacegeeks4777/1647902927494/a2bd785829837950d5b623aeb0f31a56e7b047fe?sender=u4a4af70ca99fea5fb7f08782

- [x] Convert EN from PDF -> HTML (using Adobe), option to remove images , log in with media@pg
- [x] If possible, find headings and insert # to make headings in markdown
- [x] Convert EN from HTML -> markdown (using a JS script, see browserling and many other similar scripts), see #1845
- [x] Cleanup, scripted and/or manual
- [x] Handle having topics from old (in some locales) and new NCG (in some other locales) in the app at the same time #1846
- [x] Alysha: Annotations with topic headings, taxonomy, etc
- [ ] Brandon: Related topics need to be computed
- [ ] Transfer some annotations to all the other languages: Topic title, topic id
- [x] Translate content into possible additional languages
- [ ] Automatic splitting up into separate files just like we do with the MB start win doc https://github.com/pg-irc/pathways-mongo/issues/92
- [ ] (MB releases here?)
- [ ] Convert all the other languages from PDF -> HTML 
- [ ] Convert all the other languages from HTML -> markdown
- [ ] Annotate topics with headings (in various languages) and ids (in English) just like we do for MB content
- [ ] Automatic splitting up of all the other languages too
- [ ] Profit!!!
