### ISSUE TITLE
Search: thin thread implementation

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#833]
Implement a simple service search UX. 
[User Stories](https://docs.google.com/document/d/1alwa7mx1_av2_Sc24t3VnlRwOu71pNGr5y1CBsCM3oc/edit#heading=h.hx7n6srmjyr)

### Acceptance Criteria 
- [ ] Search result is a list of services only, not organizations
- [ ] Sorted by lat/long and search terms as per Algolia's current behaviour
- [ ] Implement service list page and an organization detail page
- [ ] Mocks (fleshed out, not thin thread) for service list, service detail and organization detail with buttons leading to feedback pages. Mocks for feedback pages are out of scope for this story.

**Comment by cherrielam** [comment]
The preliminary mocks are now available here. Please note that they are NOT recently tested, so implement with caution 🙂

### Mocks
1) **Zeplin:** [**See mocks here**](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/dashboard?seid=5c476c88d2cd65386e4e49b2) - please see section titled "Search (WIP)"
_Note: there are two versions of the search results screen: 1) [organization result & services results](https://zpl.io/VxrWMdw) and 2) [only shows services results](https://zpl.io/agWEZ09)_

2) **Click-through prototype** to see [flow](https://sketch.cloud/s/2k7wM/a/3pYK8D/play)

### Notes/Disclaimers:
- For the Search UI in other (non-English) languages --> the text within the search bar should say "Search for services (only in English)" 
- Grey box & Grey circle --> These are meant to be images of the organization, eg. Organization Logo. These are **nice to have**
- Where it says: "Why is this information in English?" --> This is changed as a result of the findings from testing partial localization, but the change **needs to be tested**
- The tabs that toggle between "About" and "Services" on ORG DETAIL --> This is an attempt at showing the org detail and its services together without being an overwhelmingly long page. We are unclear yet if this is a usable/accessible yet. This **needs to be tested**
- Bookmark and overflow menu --> early attempts of UI for saving, sharing etc. These **need to be tested**

**Comment by cherrielam** [comment]
Tagging @rasmus-storjohann-PG for review and to ask me any questions!

**Comment by rasmus-storjohann-PG** [comment]
Sub stories:
* Search string input screen, [mocks here](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa44f3ff161cec799ad)
* Search location input screen, [mocks here](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa42db2bc777d20277d)
* Service list with search results, [mocks here](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5d929aa5bb3cda171b4e0de9), but with simplifications: Use existing `ServiceListComponent` but populated with data from algolia. Need plumbing to make data from our REST end point and from Algolia into the same client side data format Service in `/pathways-frontend/src/stores/services/types.ts`. This means that the details of how the services appear in the list will match the current service listing in the app, not the service listing in the mock.
* Bookmark service: Plumbing
* Surface bookmarked services on the bookmark page

**Comment by rasmus-storjohann-PG** [comment]
See substories #838 , #839, #840, #841 and #842.

**Comment by ArtiBPG** [comment]
closing because Rasmus created new ones.

**Comment by cherrielam** [comment]
Closing because all issues have been completed
