### ISSUE TITLE
Search: keyword search polish

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#936]
**1.** #938 Split search into two input fields. With the aim to allow users to search conveniently, we want to provide an updated search experience where users could adjust both the keyword and the location field together instead of having to navigate between one to another. Users may optionally specify location, so search works with or without location set.

Search is not "live", user has to click button "Search" (in upper right of mocks) to make the search happen. 

Stretch goal is to support live search if it is easy. In this case, there is no "Search" button, there is a ["Done"](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/screen/5df04f8aa47344b0f512e033) button that collapses the two input fields into one.

* Initial screen: 
https://zpl.io/VkzBBWW
* With focus on key words input 
https://zpl.io/Vq5ZZLG
* With focus on location input 
https://zpl.io/2ZB99ZE
* With both fields are populated, note truncation of search strings to save screen space 
https://zpl.io/a3DkZpN

**2A.** #939 An empty screen for Search. Logically, it doesn't make sense for the users to be able to see a list of services without having any input. Therefore, an empty screen is presented to prompt the users to search instead of confusing the users with a random service list. https://zpl.io/VkzBBWW

**2B.** #939 A dialogue to notify the users about partial localization. This is important because currently, our service information cannot be displayed in languages other than English. As a user, they will want to understand why isn't there a translation. Note that, this is only a half step as part of our goal is to remove the language barrier in accessing information. See mock for 2A.

**3.** #940 Different error states to guide users to search. For example, when wifi is not on, or when location access isn't granted. Whenever an error occurs, users will want to know how to fix it (or even better, prevent the error from ever happening again). Therefore, it is our responsibility to provide guidance for users to take action. Upon further investigation, there are three errors states to be included: 
* No matched results
https://zpl.io/V0jkkpR
* No internet access, note this state already exists for "Search service near me" and can be reused
https://zpl.io/V15kWoJ
* Invalid location
https://zpl.io/b6okR8N

**4.** #913 Hide "My location" when location services are disabled.

**5.** #935  Search analytics

**6.** #892  Discovered bug where bookmark causes refresh and lost scroll position

**7.** #1012  Load more services trigger service list to rerender

**8.** #957 Collapse search fields 

**9.** #958 Collapse navigation tab on scroll

Additional criteria
- [ ] A loading state to appear while live search is happening.

**Link to the interaction deck:** https://drive.google.com/open?id=1Q70fNaakoOWnogR6Ws9_sjBkFGyqdpmW

**Comment by aron-chen-pg** [comment]
**Search QA for #938 **
_Tested device: Samsun 8_

- [ ] Incorrect font for both search input field - ensure it’s Avenir Book.
- [ ] Opacity for texts within search input fields should change according to its state: 1) with placeholder text - 80%, 2) placeholder text but focused - 30%, 3) with user input - 100%.
- [ ] Typing indicator should be in white instead of green.
- [ ] “X” icon for both search input fields should be white instead of black.
- [ ] Is there a way to show loading state when service listing is updating? (i.e. a spinning wheel)
- [ ] “My location” button should have a right-padding of 16dp. Refer to https://zpl.io/2ZB99ZE. Please provide me both the left and right padding for the search input field and “My Location” button.
- [ ] Location icon needs more investigation (visually doesn’t align with the search icon above).
- [ ] Touch area for the “X” icon is too small. Refer to deck: https://drive.google.com/open?id=1Q70fNaakoOWnogR6Ws9_sjBkFGyqdpmW.
- [ ] Invalid location should display no services but error state instead.
- [ ] Regarding the “load more” button, I thought Algolia has the capability to load more services on its own as you scroll down? For example, can we automatically load 20 more services as users scroll down to the bottom of the list? That would be the more ideal experience instead of requiring the users to manually load more.

**Comment by aron-chen-pg** [comment]
Regarding #938, with the updated design, we no longer have the "Done" button (nor "Cancel"). I've updated the Zeplin link within this issue to reflect the change.

**Comment by ArtiBPG** [comment]
@ian-lin-PG you can work on these:
> * [ ]  Incorrect font for both search input field - ensure it’s Avenir Book.
> * [ ]  Opacity for texts within search input fields should change according to its state: 1) with placeholder text - 80%, 2) placeholder text but focused - 30%, 3) with user input - 100%.
> * [ ]  Typing indicator should be in white instead of green.
> * [ ]  “X” icon for both search input fields should be white instead of black.
> * [ ]  “My location” button should have a right-padding of 16dp. Refer to https://zpl.io/2ZB99ZE. Please provide me both the left and right padding for the search input field and “My Location” button.
> * [ ]  Touch area for the “X” icon is too small. Refer to deck: https://drive.google.com/open?id=1Q70fNaakoOWnogR6Ws9_sjBkFGyqdpmW.

____________
These are not tasks, needs more discussion @aron-chen-pg 
> * [ ]  Is there a way to show loading state when service listing is updating? (i.e. a spinning wheel)
> * [ ]  Location icon needs more investigation (visually doesn’t align with the search icon above).
> * [ ]  Regarding the “load more” button, I thought Algolia has the capability to load more services on its own as you scroll down? For example, can we automatically load 20 more services as users scroll down to the bottom of the list? That would be the more ideal experience instead of requiring the users to manually load more.
> * [ ]  Location should also perform live search.

Do we have a mock for error state?
> * [ ]  Invalid location should display no services but error state instead.

**Comment by ian-lin-PG** [comment]
The UI improvements from the last comments have been addressed in this [PR](https://github.com/pg-irc/pathways-frontend/pull/986).

**Comment by rasmus-storjohann-PG** [comment]
Closing this epic as it is no longer useful for tracking search issues. See #1140 and #1141 for remaining search issues.
