### ISSUE TITLE
Add GA tracking for Questionnaire/Recommendations

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#949]
We would like to confirm that there is Google Analytics tracking/add GA tracking in order to understand the following (this is referenced in issue #789 ) :
- How many users click on "Go back to questionnaire"?
- Do people actually go back to the questionnaire and answer more questions?
- How many people actually see the "New topics recommended" dialogue?
- How many users close the questionnaire before completing?

### Acceptance Criteria 
- [ ] New functionality is consistent with commitments in our privacy policy 
- [ ] GA tracks # user clicks on "Go back to questionnaire"
- [ ] GA tracks what happens after user clicks "Go back to questionnaire" (we want to know how many users click return to questionnaire and actually click stuff within the questionnaire, eg. answer more questions)
- [ ] GA tracks how many users see the "New topics recommended" dialogue
- [ ] GA tracks how many users close questionnaire before completing/drop off point in the questionnaire

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment]
@ian-lin-PG and @cherrielam to review current GA data and determine need for additional GA data points.

**Comment by rasmus-storjohann-PG** [comment]
Need to have a conversation with Jen on strategy around this
